import mockSoapJPG from "../assets/mockSoap.jpg"
import Slide1 from "../assets/slides/4.png"
import Slide2 from "../assets/slides/2.png"
import Slide3 from "../assets/slides/3.png"
import Slide4 from "../assets/slides/1.png"
import Slide5 from "../assets/slides/5.png"


export const products = [
    {
        id: 1,
        name: "Рідке мило  Black Mamba liquid soap",
        description: "Чорне рідке мило, упаковане у перероблений пластиковий дозатор",
        image: Slide1,
        price: 200,
        reviewsCount: 458,
        rating: 4.7,
        flavor: "Кокос",
        size: "200*300мм",
        constructor: true,
    },
    {
        id: 2,
        name: "Тверде мило Black Mamba hand soap",
        description: "Чорне тверде мило для рук, упаковане у коробку з екологічно чистого картону",
        image: Slide2,
        price: 220,
        reviewsCount: 432,
        rating: 4.6,
        flavor: "Мед",
        size: "200*300мм",
        constructor: true,
    },
    {
        id: 3,
        name: "Комплект Total Black Mamba",
        description: "Комплект з Black Mamba liquid soap,shampoo,shower gel. Упаковані у екологічно чистий пластиковий дозатор",
        image: Slide3,
        price: 180,
        reviewsCount: 375,
        rating: 4.5,
        flavor: "Цитруси",
        size: "200*300мм",
        constructor: true,
    },
    {
        id: 4,
        name: "Тверде мило Black Mamba",
        description: "Чорне тверде мило для рук, упаковане у коробку з екологічно чистого картону",
        image: Slide4,
        price: 200,
        reviewsCount: 389,
        rating: 4.7,
        flavor: "Морський бриз",
        size: "200*300мм",
        constructor: true,
    },
    {
        id: 5,
        name: "Антисептик Black Mamba antiseptic",
        description: "Антисептик Black Mamba. Упакований у екологічно чистий пластиковий дозатор",
        image: Slide5,
        price: 280,
        reviewsCount: 601,
        rating: 4.9,
        flavor: "Троянда",
        size: "200*300мм",
        constructor: true,
    },
    {
        id: 6,
        name: "Мило Coconut Paradise",
        description: "Ніжне мило з ароматом кокоса, огортає шкіру ніжним ароматом тропіків.",
        image: mockSoapJPG,
        price: 230,
        reviewsCount: 488,
        rating: 4.7,
        flavor: "Кокос",
        size: "200*300мм",
        constructor: false
    },
    {
        id: 7,
        name: "Мило Green Tea Harmony",
        description: "Ароматне мило з екстрактом зеленого чаю, освіжає і доглядає за шкірою.",
        image: mockSoapJPG,
        price: 210,
        reviewsCount: 409,
        rating: 4.6,
        flavor: "Зелений чай",
        size: "200*300мм",
        constructor: false
    },
    {
        id: 8,
        name: "Мило Vanilla Dream",
        description: "Мило з нотками ванілі, створює атмосферу затишку і комфорту в ванній.",
        image: mockSoapJPG,
        price: 240,
        reviewsCount: 522,
        rating: 4.8,
        flavor: "Ваніль",
        size: "200*300мм",
        constructor: false
    },
    {
        id: 9,
        name: "Мило Exotic Mango",
        description: "Ароматне мило з нотками екзотичного манго, освіжає і зволожує шкіру.",
        image: mockSoapJPG,
        price: 260,
        reviewsCount: 451,
        rating: 4.6,
        flavor: "Манго",
        size: "200*300мм",
        constructor: false
    },
    {
        id: 10,
        name: "Мило Shea Butter Delight",
        description: "Мило з маслом ши, живить і зволожує шкіру, робить її м'якою і доглянутою.",
        image: mockSoapJPG,
        price: 270,
        reviewsCount: 489,
        rating: 4.8,
        flavor: "Масло ши",
        size: "200*300мм",
        constructor: false
    },
    {
        id: 11,
        name: "Мило Tea Tree Cleanse",
        description: "Мило з маслом чайного дерева, ефективно очищає шкіру і запобігає появі прищів.",
        image: mockSoapJPG,
        price: 190,
        reviewsCount: 372,
        rating: 4.5,
        flavor: "Чайне дерево",
        size: "200*300мм",
        constructor: false
    },
    {
        id: 12,
        name: "Мило Almond Bliss",
        description: "Мило з нотками мигдалю, живить і зволожує шкіру, робить її бархатистою і гладкою.",
        image: mockSoapJPG,
        price: 220,
        reviewsCount: 411,
        rating: 4.6,
        flavor: "Мигдаль",
        size: "200*300мм",
        constructor: false
    },
    {
        id: 13,
        name: "Мило Aloe Vera Soothe",
        description: "Заспокійливе мило з екстрактом алое вера, знімає подразнення і зволожує шкіру.",
        image:mockSoapJPG,
        price: 200,
        reviewsCount: 389,
        rating: 4.7,
        flavor: "Алое вера",
        size: "200*300мм",
        constructor: false
    },
    {
        id: 14,
        name: "Мило Eucalyptus Refresh",
        description: "Освіжаюче мило з евкаліптом, має антисептичні властивості та поліпшує дихання.",
        image: mockSoapJPG,
        price: 210,
        reviewsCount: 398,
        rating: 4.6,
        flavor: "Евкаліпт",
        size: "200*300мм",
        constructor: false
    },
    {
        id: 15,
        name: "Мило Chamomile Calm",
        description: "Мило з екстрактом ромашки, заспокоює шкіру та покращує її стан.",
        image: mockSoapJPG,
        price: 180,
        reviewsCount: 355,
        rating: 4.4,
        flavor: "Ромашка",
        size: "200*300мм",
        constructor: false
    }
]